# Generated by Django 4.2.7 on 2023-11-25 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_as_leader', to=settings.AUTH_USER_MODEL),
        ),
    ]
